# Generated by Django 3.1.7 on 2021-04-02 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Adver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(default='Description for current adver')),
                ('image', models.ImageField(upload_to='pics/%Y/%m/%d')),
                ('price', models.CharField(max_length=10)),
                ('addition_date', models.DateField(auto_now_add=True)),
                ('actual', models.BooleanField(default=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertising.category')),
            ],
        ),
    ]
